

# Setup
title:               SnowDeer's Programming Holic
tagline:             'based on Lanyon theme'
description:         ''
url:                 http://snowdeer.github.io
baseurl:             "http://snowdeer.github.io/"
paginate:            5

# About/contact
author:
  name:              SnowDeer
#  url:               https://twitter.com/mdo
  email:             snowdeer0314@gmail.com

# Custom vars
version:             1.0.0
