# Site Info
title: Code Holic
tagline: "jhbaaa blog"
description: '삽질쟁이 jhbaaa의 블로그 입니다'
baseurl: ""
url: https://jhbaaa.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0

# About/contact
author:
  name: jhbaaa
  description: jhbaaa.
  contact:
    linkedin:  https://www.linkedin.com/in/jaehyunbaek
    github:    https://github.com/jhbaaa
    facebook:  https://www.facebook.com/happyroter
    #twitter:   https://twitter.com/
    email:     mailto:happyroter@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/categories/'
  Categories:
    - '/blog/categories/'
    # - { Categories All: '/blog/categories/' }
    # - { Linux: '/blog/categories/#linux' }

    - { android: '/blog/categories/#android' }

    - { java: '/blog/categories/#java' }
    - { c/c++: '/blog/categories/#C/C++' }
    - { python: '/blog/categories/#python' }
    
    - { algorithm : '/blog/categories/#algorithm' }
    - { etc: '/blog/categories/#etc' }
    
  Tags: 
    - '/blog/tags/'

  Search :
    - '/blog/tags/'

  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/hello.jpg
  caption: 어서오세요! jhbaaa의 블로그 입니다 :)

# Pugl-In
mathjax: true
google_analytics_token: 'UA-131296122-1'
disqus_short_name: 'jhbaaas-blog'

# deployment
host: 0.0.0.0
port: 4000
