

# Setup
title:               SnowDeer's Programming Holic
tagline:             'for Power Programmer'
description:         ''
url:                 http://snowdeer.github.io
baseurl:             "http://snowdeer.github.io"
paginate:            5
markdown: kramdown

# About/contact
author:
  name:              SnowDeer
#  url:               
  email:             snowdeer0314@gmail.com

# Custom vars
version:             1.0.0
