# Site Info
title: Code Holic
tagline: 'SnowDeer''s Code Holic'
description: '프로그래밍을 좋아하는 개발자 SnowDeer의 블로그입니다.'
baseurl: ""
url: https://snowdeer.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0

# About/contact
author:
  name: snowdeer
  description: 프로그래밍을 좋아하는 개발자 SnowDeer입니다.
  contact:
    #linkedin:  https://www.linkedin.com/in/snowdeer
    github:    https://github.com/snowdeer
    facebook:  https://www.facebook.com/snowdeer.seo
    #twitter:   https://twitter.com/snowdeer
    email:     mailto:snowdeer0314@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/categories/'
  Categories:
    - '/blog/categories/'
    # - { Categories All: '/blog/categories/' }
    - { 블로그: '/blog/categories/#블로그' }
    - { Android: '/blog/categories/#android' }
    - { C++: '/blog/categories/#c' }
    - { Python: '/blog/categories/#python' }
    - { 알고리즘: '/blog/categories/#알고리즘' }
    - { Tips: '/blog/categories/#tips' }
    - { 개발상식: '/blog/categories/#개발상식' }
    - { 머신러닝: '/blog/categories/#머신러닝' }
    - { S/W Architecture: '/blog/categories/#s-w-architecture' }
    - { 디자인패턴: '/blog/categories/#디자인패턴' }
    - { Linux: '/blog/categories/#linux' }
    - { 라즈베리파이: '/blog/categories/#라즈베리파이' }
    - { BlockChain: '/blog/categories/#blockchain' }

    #- { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/hello_page.jpg
  caption: 안녕하세요. 반갑습니다. 다같이 프로그래밍을 공부해봐요. ^^;

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-74926912-1' # leave blank if you don't want google analytics
disqus_short_name: 'snowdeer' # leave blank if you don't want disqus
